
.PHONY: all clean check perf

all:
	(cd unit; $(MAKE) all)
	(cd kat; $(MAKE) all)

clean:
	(cd unit; $(MAKE) clean)
	(cd kat; $(MAKE) clean)

check:
	(cd unit; $(MAKE) check)
	(cd kat; $(MAKE) check)

perf:
