
.PHONY: all clean check perf individual

all:
	(cd combined; $(MAKE) all)

clean:
	(cd combined; $(MAKE) clean)

check:
	(cd combined; $(MAKE) check)

perf:
	(cd combined; $(MAKE) all)

individual:
	(cd individual; $(MAKE) all)
